### ISSUE TITLE
Update Code of Conduct link on pre-reg page

### ISSUE THREAD

**Issue by jcooter** [magfest/magclassic#66]
The current link to the Code of Conduct links to the fest website, which is the incorrect look & feel for labs.  Once the Code of Conduct is present on the labs site, we should update the link.

**Comment by binary1230** [comment]
Quick note: I think what you're saying here is you'd like a link to a
restyled copy of the code of conduct. If so that's cool.

If you guys are anticipating changes to code of conduct text, I'd like that
to be a conversation before any changes are made

On Mar 26, 2017 11:02 PM, "Joe Cooter" <notifications@github.com> wrote:

The current link to the Code of Conduct links to the fest website, which is
the incorrect look & feel for labs. Once the Code of Conduct is present on
the labs site, we should update the link.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/magfest/magclassic/issues/66>, or mute the thread

**Comment by jcooter** [comment]
@binary1230 Correct, this is only a Look&Feel issue
