### ISSUE TITLE
"Want to kick in extra?" options look weird

### ISSUE THREAD

**Issue by RobRuana** [magfest/magclassic#70]
Are the supporter options supposed to look like this?

![screen shot 2017-04-06 at 9 37 03 pm](https://cloud.githubusercontent.com/assets/2592431/24785937/85811366-1b12-11e7-8da3-5c6f9f77e2d7.png)

**Comment by migetman9** [comment]
No. I believe they used to have Glyphicons in them, but I could be wrong.

**Comment by RobRuana** [comment]
They also seem really tall, is that by design?

**Comment by migetman9** [comment]
I cannot speak to the intended design as I was not a part of it.

**Comment by jcooter** [comment]
The config isn't even remotely final yet, so I've been chalking the supporter issues up to that.  This is the relevant config section:

`uber::config::donation_tier_descriptions:`
  no_thanks:
    name: "No thanks"
    icon: ""
    description: "No thanks"
    link: ""
  shirt:
    name: "Shirt"
    icon: "../static/icons/iconshirt.png"
    description: "Ribbon|T-Shirt"
    link: "../static_views/ribbon.html|../static_views/tshirt.html"
  supporter_pack:
    name: "Supporter Pack"
    icon: "../static/icons/heart-necklace.png"
    description: "Upgraded electronic badge|Swag Bag"
    link: ""
  super_supporter:
    name: "Super Supporter"
    icon: "../static/icons/menace.png"
    description: "More upgraded electronic badge|Something else"
    link: ""`

My guess is the static files are in the super mag plugin and need to move, which is fine because we probably need to pick different icons anyway.

It's also possible that not having links could cause some weird behavior - but we don't have anything to link to yet.

**Comment by RobRuana** [comment]
Very cool! I've added this issue to the preregistration milestone. I'm gonna make the following changes to the layout:
* Add the missing icons from the super mag plugin (we can change what they actually look like later)
* Make the selection buttons shorter
* Add some margins to the selection buttons (enough to match the "Registration type" buttons)
* Tweak some of the responsive layout (At smaller screen sizes the buttons overflow off the side of the page)

**Comment by binary1230** [comment]
Fyi the layout code for those buttons is technical debt Twilight zone

Be prepared to spend some extra time untangling this if you're trying to
make changes

**Comment by kitsuta** [comment]
Yeah, I would definitely put any optional changes to the kick-in selection as very low priority, it is a last-minute mess afaik.
